# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: configure-deps
description: Configure dependency versions used by rs-dpr-service, to match versions used by processors.

inputs:
  dep-name:
    description: Unique name for these dependency versions, e.g. 'py<python_version>-<dask_version>'
    required: true
  python-version:
    description: Python version
    required: true
  dask-version:
    description: Dask version
    required: true

outputs:
  temp-branch:
    description: Are we using a temporary branch ?
    value: ${{ steps.configure.outputs.temp-branch }}
  github-ref:
    description: Github branch that will be used in this workflow (current or temp branch)
    value: ${{ steps.configure.outputs.github-ref }}
  github-ref_name:
    description: Github branch that will be used in this workflow (current or temp branch)
    value: ${{ steps.configure.outputs.github-ref_name }}
  python-version:
    description: Python version
    value: ${{ inputs.python-version }}
  dask-version:
    description: Dask version
    value: ${{ inputs.dask-version }}
  poetry-version:
    description: Poetry version
    value: ${{ steps.configure.outputs.poetry-version }}

runs:
  using: "composite"
  steps:
    - id: configure
      name: Configure dependency versions
      env:
        # Current branch name (or source branch for a pull request)
        BRANCH_NAME: ${{ case(github.event_name == 'pull_request', github.event.pull_request.head.ref, github.ref_name) }}
        DASK_VERSION: ${{ inputs.dask-version }}
        DEP_NAME: ${{ inputs.dep-name }}
      run: |
        set -x

        # Extract the poetry version from the lock file in its header line:
        # This file is automatically @generated by Poetry <version> and should not be changed by hand.
        match="generated by Poetry ([^ \t]*)"
        [[ $(grep -E "$match" poetry.lock) =~ $match ]] && poetry_version=${BASH_REMATCH[1]}

        # pyproject.toml contains the line: 'dask = {extras = ["xxx"], version = "yyy"}'
        # We change the dask version.
        sed -i "/^dask[ \t=]/s/version[^,}]*/version = \"$DASK_VERSION\"/g" pyproject.toml

        # If the pyproject file changed, install poetry and rebuild the lock file
        if ! git diff --exit-code pyproject.toml; then
          pip install --only-binary=:all: poetry==$poetry_version
          poetry lock
        fi

        # NOTE: the python version does not seem to change anything to the poetry.lock file
        # so we don't rebuild the lock if the python version changed.

        # If the lock file changed
        if ! git diff --exit-code poetry.lock; then

          # Create a temp branch from the current branch name
          temp_branch=true
          temp_branch_name="${BRANCH_NAME}___TEMP-${{ github.run_id }}/${DEP_NAME}"
          github_ref="refs/heads/${temp_branch_name}"
          github_ref_name="${temp_branch_name}"

          git checkout -b $temp_branch_name
          git add pyproject.toml poetry.lock
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -m "Update dependencies for ${DEP_NAME}"
          git push --set-upstream origin $temp_branch_name

        # If the lock file didn't change, keep the current branch or pull request
        else
          temp_branch=false
          github_ref="${{ github.ref }}"
          github_ref_name="${{ github.ref_name }}"
        fi

        # Save values
        echo "temp-branch=$temp_branch" >> "$GITHUB_OUTPUT"
        echo "github-ref=$github_ref" >> "$GITHUB_OUTPUT"
        echo "github-ref_name=$github_ref_name" >> "$GITHUB_OUTPUT"
        echo "poetry-version=$poetry_version" >> "$GITHUB_OUTPUT"
      shell: bash
