#!/usr/bin/env bash
# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Configure dependency versions used by rs-dpr-service, to match versions used by processors.

set -euo pipefail
set -x

# We download the json file that contains the sets of dependency versions needed by the different processors.
# Its content should be something like:
# {"deps": [
# {"python_version": "3.11.7", "dask_version": "2024.5.2"},
# {"python_version": "3.13.12", "dask_version": "2026.1.2"},
# ...

# We test to download from the rs-workflow-env repo, first with the same branch name, then with 'develop'
deps_file=dask-eopf-versions.json
url="https://raw.githubusercontent.com/RS-PYTHON/rs-workflow-env/refs/heads/WHAT_BRANCH/docker/eopf/resources/${deps_file}"
wget --max-redirect=0 "${url/WHAT_BRANCH/"$BRANCH_NAME"}" || wget --max-redirect=0 "${url/WHAT_BRANCH/develop}"
cat $deps_file

dep_names="[]" # list of py<python-version>-<dask-version>
completed_deps="[]" # fields completed with temp_branch, github_ref, ...

# Extract the poetry version from the lock file in its header line:
# This file is automatically @generated by Poetry <version> and should not be changed by hand.
match="generated by Poetry ([^ \t]*)"
[[ $(grep -E "$match" poetry.lock) =~ $match ]] && poetry_version=${BASH_REMATCH[1]}

# For each set of versions
for dep in $(jq -c '.deps[]' $deps_file); do
    python_version=$(jq -r '."python_version"' <<< $dep)
    dask_version=$(jq -r '."dask_version"' <<< $dep)
    dep_name="py${python_version}-${dask_version}"

    # Add dep_name to json array
    dep_names=$(jq ". += [\"$dep_name\"]" <<< $dep_names)

    # If we don't create temp branch, we only save the current dependency info
    if [[ $CREATE_TEMP_BRANCHES != true ]]; then
        completed_deps=$(jq ". += [$dep"] <<< "$completed_deps")
        continue
    fi

    # Back to the original git branch
    git fetch && git checkout $BRANCH_NAME

    # pyproject.toml contains the line: 'python = "==xxx"'
    # We change the python version.
    sed -i "/^python[ \t=]/s/.*/python = \"==${python_version}\"/g" pyproject.toml

    # pyproject.toml contains the line: 'dask = {extras = ["xxx"], version = "yyy"}'
    # We change the dask version.
    sed -i "/^dask[ \t=]/s/version[^,}]*/version = \"${dask_version}\"/g" pyproject.toml

    # If the pyproject file changed
    if ! git diff --exit-code pyproject.toml; then

        # Create a temp branch from the current branch name
        temp_branch=true
        temp_branch_name="${BRANCH_NAME}___TEMP-${GITHUB_RUN_ID}/${dep_name}"
        github_ref="refs/heads/${temp_branch_name}"
        github_ref_name="${temp_branch_name}"

        git checkout -b $temp_branch_name
        git add pyproject.toml
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git commit -m "Update dependencies for $dep_name"
        git push --set-upstream origin $temp_branch_name

    # If the pyproject file didn't change, keep the current branch or pull request
    else
        temp_branch=false
        github_ref=$GITHUB_REF
        github_ref_name=$GITHUB_REF_NAME
    fi

    # Add fields to the current set of versions
    new_fields="{
        \"dep_name\": \"$dep_name\",
        \"temp_branch\": \"$temp_branch\",
        \"github_ref\": \"$github_ref\",
        \"github_ref_name\": \"$github_ref_name\",
        \"poetry_version\": \"$poetry_version\",
        }"
    completed_dep=$(jq ". += $new_fields" <<< "$dep")
    completed_deps=$(jq ". += [$completed_dep"] <<< "$completed_deps")
done

# Save the ci/cd matrix
matrix="{
    \"dep_name\": $dep_names,
    \"include\": $completed_deps
}"

# The output matrix should be something like:
# "dep_name": ["py3.11.7-2024.5.2", "py3.13.12-2026.1.2", ...],
# "include": [
#   {"dep_name": "py3.11.7-2024.5.2", "python_version": "...", "dask_version": "...", "temp_branch": "...", "github_ref": "xxx", "github_ref_name": "yyy", "poetry_version": "zzz" },
#   {"dep_name": "py3.13.12-2026.1.2", "python_version": "...", ...
#   ...

echo "matrix=$(jq -c . <<< $matrix)" >> $GITHUB_OUTPUT
