# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Check code quality

on:
  push:
    branches: [develop, main] # pushes on the 'develop' or 'main' branches
    tags: ['**'] # new git tags (including hierarchical tags like v1.0/beta)
  pull_request:
    types: [opened, synchronize, reopened]
    # run this worflow only for code/test related changes (avoid it for documentation)
    paths: ['**.json', '**.lock', '**.py', '**.raw', '**.sh', '**.toml', '**.yaml', '**.yml']
  workflow_dispatch:

jobs:
  configure-deps:
    runs-on: ubuntu-latest
    name: Configure dependency versions
    permissions:
      contents: write # for the git push
    outputs:
      matrix: ${{ steps.configure-deps.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - id: configure-deps
        uses: ./.github/actions/configure-deps

  update-lock:
    name: Update lock files
    needs: configure-deps
    permissions:
      contents: write # for the git push
    uses: ./.github/workflows/temp-branches.yml
    with:
      action: update-lock
      matrix: ${{ needs.configure-deps.outputs.matrix }}

  clean-temp-branches:
    name: Clean temporary branches
    needs: configure-deps
    if: always() # even if crashed or cancelled
    permissions:
      contents: write # for the git branch delete
    uses: ./.github/workflows/temp-branches.yml
    with:
      action: clean
      matrix: ${{ needs.configure-deps.outputs.matrix }}



  #         pip install --only-binary=:all: poetry==$poetry_version
  #         poetry lock

  #     - uses: cloudposse/github-action-matrix-outputs-write@81ea135d4c4f90a5220bb38304380073c571dbb8
  #       with:
  #         matrix-step-name: configure-deps
  #         matrix-key: ${{ matrix.dep-name }}
  #         # outputs: |
  #         #   deps: ${{ toJson(steps.configure-deps.outputs) }}

  # # We want to call the "check code quality" reusable workflow after having configured the dependency versions,
  # # but in github actions it's not possible to call a reusable workflow from a step, so we have to read the
  # # previous outputs and reformat them into a new matrix configuration, it's a real hassle...
  # read-configured-deps:
  #   runs-on: ubuntu-latest
  #   name: Read configured dependencies
  #   needs: [configure-deps]
  #   if: always() # even if crashed or cancelled
  #   outputs:
  #     configured-deps: ${{ steps.configure.outputs.configured-deps }}
  #   steps:
  #     - id: read-matrix
  #       uses: cloudposse/github-action-matrix-outputs-read@ddb62566e896c85614f5eeec2daa43d6d1dc6cb0
  #       with:
  #           matrix-step-name: configure-deps
  #     - id: configure
  #       run: |

  #         # It's something like {'deps': {'dep-name1': {'key1': 'value1', 'key2': 'value2'}, 'dep-name2': ...
  #         print("str input config:\n%s" % '${{ steps.read-matrix.outputs.result }}')

  #         # And we want to convert this into a github matrix configuration as the one from the previous job
  #         import json
  #         deps = ${{ steps.read-matrix.outputs.result }}["deps"]
  #         print("json input config:\n%s" % json.dumps(deps, indent=2))

  #         matrix = {
  #           "dep-name": sorted(list(deps.keys())),
  #           "include": [
  #             {"dep-name": dep_name, **values}
  #             for dep_name, values in deps.items()
  #           ]
  #         }
  #         print("json output config:\n%s" % json.dumps(matrix, indent=2))

  #         # Save output
  #         import os
  #         with open(os.environ["GITHUB_OUTPUT"], "a") as opened:
  #           opened.write(f"configured-deps={json.dumps(matrix)}")
  #       shell: python

  # check-code-quality:
  #   name: Check code quality
  #   needs: read-configured-deps
  #   strategy:
  #     fail-fast: false
  #     matrix: ${{ fromJson(needs.read-configured-deps.outputs.configured-deps) }}
  #   uses: RS-PYTHON/actions/.github/workflows/reusable-check-quality.yml@feat-rspy1044/multiple-dask-versions
  #   with:
  #     caller-repository: ${{ github.repository }}
  #     caller-ref: ${{ matrix.github-ref }}
  #     caller-ref_name: ${{ matrix.github-ref_name }}
  #     python-version: ${{ matrix.python-version }}
  #     cov-dirs: rs_dpr_service
  #     artifact-prefix: "${{ matrix.dep-name }}_"
  #   secrets:
  #     SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #   permissions:
  #     contents: write # for apache/skywalking-eyes/header
  #     pull-requests: write # for apache/skywalking-eyes/header and phwt/sonarqube-quality-gate-action

  # clean-temp-branches:
  #   runs-on: ubuntu-latest
  #   name: Clean temporary branches
  #   needs: [read-configured-deps, check-code-quality]
  #   if: always() # even if crashed or cancelled
  #   permissions:
  #     contents: write # for the git push
  #   steps:
  #     - uses: actions/checkout@v6
  #     - run: |
  #         # It's something like {..., "include": [{..., "temp-branch": "true|false", "github-ref": <branch-name>}]}
  #         print("str config:\n%s" % '${{ needs.read-configured-deps.outputs.configured-deps }}')

  #         import json
  #         config = ${{ needs.read-configured-deps.outputs.configured-deps }}
  #         print("json config:\n%s" % json.dumps(config, indent=2))

  #         import subprocess
  #         for branch in config["include"]:
  #           branch_name=branch["github-ref"]
  #           if branch["temp-branch"] == "true":
  #             print(f"Delete branch: {branch_name!r}")
  #             subprocess.run(["git", "push", "-d", "origin", branch_name])
  #           else:
  #             print(f"Don't delete branch: {branch_name!r}")
  #       shell: python

  check-tasktables:
    runs-on: ubuntu-latest
    name: Check tasktables (json schema)
    steps:
      - uses: actions/checkout@v6
      - name: Validate tasktables
        run: pipx run check-jsonschema --schemafile schemas/TaskTable.schema.json config/TaskTable_*.json
